{
 "title": "Nginx Monitoring",
 "tags": [ "Nginx" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "2xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "rate(syslog_responses_by_class_total{class=\"2xx\"}[$__rate_interval])",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "3xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "rate(syslog_responses_by_class_total{class=\"3xx\"}[$__rate_interval])",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "rate(syslog_responses_by_class_total{class=\"4xx\"}[$__rate_interval])",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "rate(syslog_responses_by_class_total{class=\"5xx\"}[$__rate_interval])",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(syslog_request_latency_seconds_sum[$__rate_interval])\r\n/\r\nrate(syslog_request_latency_seconds_count[$__rate_interval])",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Requests Total Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(nginx_requests_total[$__rate_interval])",
     "legendFormat": "Requests Total Rate"
    }
   ]
  },
  {
   "title": "Request By IP Address",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(syslog_requests_by_ip[$__rate_interval])",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "nginx_active_connections", "legendFormat": "{{__name__}}" },
    { "expr": "nginx_waiting_connections", "legendFormat": "{{__name__}}" },
    { "expr": "nginx_writing_connections", "legendFormat": "{{__name__}}" },
    { "expr": "nginx_reading_connections", "legendFormat": "{{__name__}}" }
   ]
  }
 ]
}